package lifecube.entity.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Setter;
import lombok.ToString;

@Setter
@ToString
@DynamoDBTable(tableName = "submissions")
public class SubmissionEntity {

  private String id;
  private String type;
  private String text;

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  @DynamoDBAttribute
  public String getText() {
    return text;
  }

  @DynamoDBAttribute
  public String getType() {
    return type;
  }
}
